###  Creates patient in the entity
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Aman Circuit Breaker Test",
  "email": "aman_cb_account31@gmail.com",
  "address": "123, Jenkins Street",
  "dateOfBirth": "2002-12-31",
  "registeredDate": "2025-04-21"
}

###