spring:
  application:
    name: patient-service

#  UNCOMMENT TO USE IN MEMORY DATABASE OUTSIDE OF DOCKER
#  h2:
#    console:
#      path: /h2-console
#
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: admin_viewer
#    password: admin
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#
#  sql:
#    init:
#      mode: always

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

server:
  port: 4000

logging:
  level:
    root: info

resilience4j:
  circuitbreaker:
    instances:
      billingService:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      billingRetry:
        max-attempts: 3
        wait-duration: 500ms


